<?php

namespace Application\ServiceConstructorBundle\Repository;

/**
 * ControllerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControllerRepository extends \Doctrine\ORM\EntityRepository
{
}
