<?php

namespace Application\ServiceConstructorBundle\Repository;

/**
 * ServiceMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
