application_seo:
    resource: "@ApplicationSeoBundle/Resources/config/routing.yml"
    prefix:   /

application_cms:
    resource: "@ApplicationCMSBundle/Resources/config/routing.yml"
    prefix:   /

application_service_constructor:
    resource: "@ApplicationServiceConstructorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# SonataAdminBundle
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#UserBundle
bundles_user:
    resource: "@BundlesUserBundle/Resources/config/routing/security.xml"

bundles_user_admin:
    resource: "@BundlesUserBundle/Resources/config/routing/admin_security.xml"
    prefix:   /admin

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile