application_service_constructor:
    resource: "@ApplicationServiceConstructorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
