<?php

namespace Application\CMSBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlocks($area , $template , $locale)
    {
        $qb = $this->createQueryBuilder('b')
            ->andWhere('b.isActive = 1')
            ->andWhere('b.locale = :locale')  
            ->join('b.blockToTemplates', 'btt','WITH', 'btt.template = :template' )
            ->andWhere('btt.area = :area')
            ->orderBy('btt.orderNum', 'ASC')
            ->setParameter('template', $template)
            ->setParameter('area', $area)
            ->setParameter('locale', $locale);   
       
      return $qb->getQuery()->getResult();
    }
}
