Application\ServiceConstructorBundle\Entity\Action:
    type: entity
    table: sc_actions
    repositoryClass: Application\ServiceConstructorBundle\Repository\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        hasRoute:
            type: boolean
        hasView:
            type: boolean
        responseType:
            type: string
            length: 255
    manyToOne:
        controller:
            targetEntity: Controller
            inversedBy: actions
            joinColumn:
                name: controller_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
