Application\ServiceConstructorBundle\Entity\Bundle:
    type: entity
    table: sc_bundles
    repositoryClass: Application\ServiceConstructorBundle\Repository\BundleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        namespace:
            type: string
            length: 255
        format:
            type: string
            length: '30'
    oneToMany:
        controllers:
            targetEntity: Controller
            mappedBy: bundle
        services:
            targetEntity: Service
            mappedBy: bundle
        entities:
            targetEntity: Entity
            mappedBy: bundle
    lifecycleCallbacks: {  }
