Application\ServiceConstructorBundle\Entity\Controller:
    type: entity
    table: sc_controllers
    repositoryClass: Application\ServiceConstructorBundle\Repository\ControllerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        bundle:
            targetEntity: Bundle
            inversedBy: controllers
            joinColumn:
                name: bundle_id
                referencedColumnName: id
    oneToMany:
        controllers:
            targetEntity: Controller
            mappedBy: controller
    lifecycleCallbacks: {  }
