Application\ServiceConstructorBundle\Entity\Entity:
    type: entity
    table: sc_entities
    repositoryClass: Application\ServiceConstructorBundle\Repository\EntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        tableName:
            type: string
            length: 255
        repository:
            type: string
            length: 255
    manyToOne:
        bundle:
            targetEntity: Bundle
            inversedBy: entities
            joinColumn:
                name: bundle_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
