Application\ServiceConstructorBundle\Entity\Entity:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        tableName:
            type: string
            length: 255
        repository:
            type: string
            length: 255
    lifecycleCallbacks: {  }
