Application\ServiceConstructorBundle\Entity\Service:
    type: entity
    table: sc_services
    repositoryClass: Application\ServiceConstructorBundle\Repository\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        bundle:
            targetEntity: Bundle
            inversedBy: services
            joinColumn:
                name: bundle_id
                referencedColumnName: id
    oneToMany:
        methods:
            targetEntity: ServiceMethod
            mappedBy: service
    lifecycleCallbacks: {  }
